name: Test custom action

on:
  workflow_dispatch:

jobs:
  test-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      
